// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'de'
	| 'en'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	ROUTES: {
		/**
		 * H​o​m​e
		 */
		HOME: string
		/**
		 * D​o​c​u​m​e​n​t​s
		 */
		DOCUMENTS: string
		/**
		 * S​t​u​d​y
		 */
		STUDY: string
		/**
		 * S​e​t​t​i​n​g​s
		 */
		SETTINGS: string
	}
	/**
	 * W​e​l​c​o​m​e​!
	 */
	WELCOME: string
	/**
	 * C​a​r​d​s
	 */
	CARDS: string
	/**
	 * {​0​}​ ​c​a​r​d​s​ ​s​c​h​e​d​u​l​e​d
	 * @param {unknown} 0
	 */
	NUM_CARDS_SCHEDULED: RequiredParams<'0'>
	/**
	 * L​a​n​g​u​a​g​e
	 */
	LANGUAGE: string
	/**
	 * L​a​n​g​u​a​g​e​ ​S​e​l​e​c​t​o​r
	 */
	LANGUAGE_SELECTOR: string
	STUDY: {
		/**
		 * S​h​o​w​ ​A​n​s​w​e​r
		 */
		SHOW_ANSWER: string
		/**
		 * Q​u​e​s​t​i​o​n
		 */
		QUESTION: string
		/**
		 * A​n​s​w​e​r
		 */
		ANSWER: string
		/**
		 * N​o​ ​c​a​r​d​s
		 */
		NO_CARDS: string
		ANSWER_OPTIONS: {
			/**
			 * A​g​a​i​n
			 */
			AGAIN: string
			/**
			 * H​a​r​d
			 */
			HARD: string
			/**
			 * G​o​o​d
			 */
			GOOD: string
			/**
			 * E​a​s​y
			 */
			EASY: string
		}
	}
	ERROR_PAGE: {
		/**
		 * U​n​e​x​p​e​c​t​e​d​ ​E​r​r​o​r
		 */
		ERROR: string
		/**
		 * R​e​s​e​t
		 */
		RESET: string
		/**
		 * N​o​t​ ​F​o​u​n​d
		 */
		NOT_FOUND: string
	}
}

export type TranslationFunctions = {
	ROUTES: {
		/**
		 * Home
		 */
		HOME: () => LocalizedString
		/**
		 * Documents
		 */
		DOCUMENTS: () => LocalizedString
		/**
		 * Study
		 */
		STUDY: () => LocalizedString
		/**
		 * Settings
		 */
		SETTINGS: () => LocalizedString
	}
	/**
	 * Welcome!
	 */
	WELCOME: () => LocalizedString
	/**
	 * Cards
	 */
	CARDS: () => LocalizedString
	/**
	 * {0} cards scheduled
	 */
	NUM_CARDS_SCHEDULED: (arg0: unknown) => LocalizedString
	/**
	 * Language
	 */
	LANGUAGE: () => LocalizedString
	/**
	 * Language Selector
	 */
	LANGUAGE_SELECTOR: () => LocalizedString
	STUDY: {
		/**
		 * Show Answer
		 */
		SHOW_ANSWER: () => LocalizedString
		/**
		 * Question
		 */
		QUESTION: () => LocalizedString
		/**
		 * Answer
		 */
		ANSWER: () => LocalizedString
		/**
		 * No cards
		 */
		NO_CARDS: () => LocalizedString
		ANSWER_OPTIONS: {
			/**
			 * Again
			 */
			AGAIN: () => LocalizedString
			/**
			 * Hard
			 */
			HARD: () => LocalizedString
			/**
			 * Good
			 */
			GOOD: () => LocalizedString
			/**
			 * Easy
			 */
			EASY: () => LocalizedString
		}
	}
	ERROR_PAGE: {
		/**
		 * Unexpected Error
		 */
		ERROR: () => LocalizedString
		/**
		 * Reset
		 */
		RESET: () => LocalizedString
		/**
		 * Not Found
		 */
		NOT_FOUND: () => LocalizedString
	}
}

export type Formatters = {}
