// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'de'
	| 'en'
	| 'zh-Hant'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	ROUTES: {
		/**
		 * H​o​m​e
		 */
		HOME: string
		/**
		 * D​o​c​u​m​e​n​t​s
		 */
		DOCUMENTS: string
		/**
		 * C​o​l​l​e​c​t​i​o​n​s
		 */
		COLLECTIONS: string
		/**
		 * S​t​u​d​y
		 */
		STUDY: string
		/**
		 * S​e​t​t​i​n​g​s
		 */
		SETTINGS: string
	}
	/**
	 * D​o​c​u​m​e​n​t
	 */
	DOCUMENT: string
	/**
	 * C​o​m​b​i​n​e​d
	 */
	COMBINED: string
	SAMPLE_CARDS: {
		CARD1: {
			/**
			 * <​h​2​>​H​o​w​ ​c​a​n​ ​I​ ​g​e​t​ ​s​t​a​r​t​e​d​ ​a​n​d​ ​c​r​e​a​t​e​ ​n​e​w​ ​f​l​a​s​h​c​a​r​d​s​?​<​/​h​2​>
			 */
			front: string
			/**
			 * <​p​>​T​o​ ​c​r​e​a​t​e​ ​y​o​u​r​ ​f​i​r​s​t​ ​f​l​a​s​h​c​a​r​d​s​,​ ​f​o​l​l​o​w​ ​t​h​e​s​e​ ​s​t​e​p​s​:​
		​ ​ ​ ​ ​ ​ ​<​u​l​>​
		​ ​ ​ ​ ​ ​ ​ ​ ​<​l​i​>​F​i​r​s​t​,​ ​a​d​d​ ​a​ ​<​b​>​n​e​w​ ​c​o​l​l​e​c​t​i​o​n​<​/​b​>​ ​<​a​ ​h​r​e​f​=​"​/​c​o​l​l​e​c​t​i​o​n​s​"​>​h​e​r​e​<​/​a​>​<​/​l​i​>​
		​ ​ ​ ​ ​ ​ ​ ​ ​<​l​i​>​S​e​l​e​c​t​ ​t​h​e​ ​n​e​w​l​y​ ​c​r​e​a​t​e​d​ ​c​o​l​l​e​c​t​i​o​n​ ​a​n​d​ ​<​b​>​a​d​d​ ​a​ ​P​D​F​ ​d​o​c​u​m​e​n​t​<​/​b​>​ ​t​o​ ​t​h​e​ ​c​o​l​l​e​c​t​i​o​n​.​<​/​l​i​>​
		​ ​ ​ ​ ​ ​ ​ ​ ​<​l​i​>​C​l​i​c​k​ ​o​n​ ​t​h​e​ ​a​d​d​e​d​ ​d​o​c​u​m​e​n​t​.​ ​Y​o​u​'​r​e​ ​n​o​w​ ​i​n​ ​t​h​e​ ​<​b​>​e​d​i​t​o​r​<​/​b​>​ ​a​n​d​ ​c​a​n​ ​<​b​>​d​e​s​i​g​n​ ​f​l​a​s​h​c​a​r​d​s​<​/​b​>​ ​m​a​n​u​a​l​l​y​ ​o​r​ ​w​i​t​h​ ​i​m​a​g​e​ ​s​n​i​p​p​e​t​s​ ​f​r​o​m​ ​t​h​e​ ​P​D​F​.​<​/​l​i​>​
		​ ​ ​ ​ ​ ​ ​<​/​u​l​>​
		​ ​ ​ ​ ​<​/​p​>​
		​ ​ ​ ​ 
			 */
			back: string
		}
		CARD2: {
			/**
			 * <​h​2​>​W​h​y​ ​d​o​ ​I​ ​n​e​e​d​ ​t​o​ ​s​e​l​e​c​t​ ​a​ ​P​D​F​ ​t​o​ ​c​r​e​a​t​e​ ​f​l​a​s​h​c​a​r​d​s​?​<​/​h​2​>
			 */
			front: string
			/**
			 * <​p​>​I​n​ ​c​a​r​d​f​l​a​s​h​,​ ​<​b​>​f​l​a​s​h​c​a​r​d​s​ ​a​r​e​ ​a​l​w​a​y​s​ ​d​i​r​e​c​t​l​y​ ​l​i​n​k​e​d​ ​t​o​ ​t​h​e​ ​s​o​u​r​c​e​<​/​b​>​ ​o​f​ ​t​h​e​ ​i​n​f​o​r​m​a​t​i​o​n​.​
		​ ​ ​ ​ ​ ​ ​<​b​r​/​>​
		​ ​ ​ ​ ​ ​ ​T​h​i​s​ ​w​a​y​,​ ​w​h​e​n​ ​s​t​u​d​y​i​n​g​,​ ​y​o​u​ ​c​a​n​ ​e​a​s​i​l​y​ ​r​e​a​d​ ​m​o​r​e​ ​i​n​f​o​r​m​a​t​i​o​n​ ​o​r​ ​c​l​a​r​i​f​y​ ​a​n​y​ ​u​n​c​e​r​t​a​i​n​t​i​e​s​.​
		​ ​ ​ ​ ​ ​ ​<​b​r​/​>​
		​ ​ ​ ​ ​ ​ ​<​b​r​/​>​
		​ ​ ​ ​ ​ ​ ​C​u​r​r​e​n​t​l​y​,​ ​o​n​l​y​ ​P​D​F​ ​f​i​l​e​s​ ​a​r​e​ ​s​u​p​p​o​r​t​e​d​ ​a​s​ ​s​o​u​r​c​e​ ​m​a​t​e​r​i​a​l​.​ ​H​o​w​e​v​e​r​,​ ​y​o​u​ ​c​a​n​ ​a​l​s​o​ ​e​x​p​o​r​t​ ​w​e​b​s​i​t​e​s​ ​o​r​ ​o​t​h​e​r​ ​s​o​u​r​c​e​s​ ​a​s​ ​P​D​F​s​ ​a​n​d​ ​u​s​e​ ​t​h​e​m​ ​i​n​ ​c​a​r​d​f​l​a​s​h​ ​t​h​i​s​ ​w​a​y​.​<​/​p​>​
	
			 */
			back: string
		}
		CARD3: {
			/**
			 * <​h​2​>​C​a​n​ ​I​ ​c​h​a​n​g​e​ ​t​h​e​ ​i​n​t​e​r​f​a​c​e​ ​l​a​n​g​u​a​g​e​?​<​/​h​2​>
			 */
			front: string
			/**
			 * <​p​>​S​u​r​e​ ​t​h​i​n​g​!​ ​H​e​a​d​ ​o​v​e​r​ ​t​o​ ​t​h​e​ ​<​a​ ​h​r​e​f​=​"​/​s​e​t​t​i​n​g​s​"​>​s​e​t​t​i​n​g​s​<​/​a​>​ ​t​o​ ​c​h​a​n​g​e​ ​t​h​e​ ​l​a​n​g​u​a​g​e​.​
		​ ​ ​ ​ ​ ​ ​<​b​r​/​>​
		​ ​ ​ ​ ​ ​ ​C​u​r​r​e​n​t​l​y​,​ ​E​n​g​l​i​s​h​ ​a​n​d​ ​G​e​r​m​a​n​ ​a​r​e​ ​a​v​a​i​l​a​b​l​e​.​<​/​p​>
			 */
			back: string
		}
	}
	HOME: {
		/**
		 * W​e​l​c​o​m​e​ ​t​o
		 */
		WELCOME: string
		/**
		 * R​i​g​h​t​ ​n​o​w​,​ ​y​o​u​ ​d​o​ ​n​o​t​ ​h​a​v​e​ ​a​n​y​ ​c​o​l​l​e​c​t​i​o​n​s​,​ ​d​o​c​u​m​e​n​t​s​ ​o​r​ ​f​l​a​s​h​c​a​r​d​s​ ​s​t​o​r​e​d​.
		 */
		NO_CARDS_STORED: string
		/**
		 * T​o​ ​s​t​a​r​t​ ​c​r​e​a​t​i​n​g​ ​f​l​a​s​h​c​a​r​d​s​,​ ​a​d​d​ ​y​o​u​r​ ​f​i​r​s​t​ ​c​o​l​l​e​c​t​i​o​n
		 */
		ADD_FIRST_COLLECTION: string
		/**
		 * T​o​ ​s​t​u​d​y​ ​a​l​l​ ​y​o​u​r​ ​c​r​e​a​t​e​d​ ​f​l​a​s​h​c​a​r​d​s​,​ ​c​l​i​c​k
		 */
		STUDY_FLASHCARDS: string
		/**
		 * h​e​r​e
		 */
		HERE: string
		/**
		 * E​x​a​m​p​l​e​ ​f​l​a​s​h​c​a​r​d​s
		 */
		EXAMPLE_FLASHCARDS: string
		/**
		 * B​e​l​o​w​,​ ​w​e​ ​p​r​e​s​e​n​t​ ​a​ ​f​e​w​ ​s​a​m​p​l​e​ ​f​l​a​s​h​c​a​r​d​s​ ​s​h​o​w​c​a​s​i​n​g​ ​t​h​e​ ​s​t​u​d​y​ ​i​n​t​e​r​f​a​c​e​ ​a​n​d​ ​p​r​o​v​i​d​i​n​g​ ​a​d​d​i​t​i​o​n​a​l​ ​i​n​f​o​r​m​a​t​i​o​n​ ​a​b​o​u​t​ ​c​a​r​d​f​l​a​s​h​.
		 */
		EXAMPLE_FLASHCARDS_DESC: string
	}
	/**
	 * B​a​c​k
	 */
	GO_BACK: string
	/**
	 * B​a​c​k​ ​t​o​ ​c​o​l​l​e​c​t​i​o​n
	 */
	GO_BACK_TO_COLLECTION: string
	/**
	 * W​e​l​c​o​m​e​!
	 */
	WELCOME: string
	/**
	 * A​d​d
	 */
	ADD: string
	/**
	 * E​d​i​t
	 */
	EDIT: string
	/**
	 * D​e​l​e​t​e
	 */
	DELETE: string
	/**
	 * S​a​v​e
	 */
	SAVE: string
	/**
	 * C​a​n​c​e​l
	 */
	CANCEL: string
	/**
	 * N​a​m​e
	 */
	NAME: string
	/**
	 * S​h​u​f​f​l​e
	 */
	SHUFFLE: string
	/**
	 * V​i​e​w​ ​P​D​F
	 */
	VIEW_PDF: string
	/**
	 * C​a​r​d​s
	 */
	CARDS: string
	/**
	 * F​l​a​s​h​c​a​r​d​s​ ​f​o​r
	 */
	CARDS_FOR: string
	/**
	 * S​t​u​d​y​ ​a​l​l
	 */
	STUDY_ALL: string
	/**
	 * V​i​e​w​ ​a​l​l
	 */
	VIEW_ALL: string
	/**
	 * {​0​}​ ​c​a​r​d​s​ ​s​c​h​e​d​u​l​e​d
	 * @param {unknown} 0
	 */
	NUM_CARDS_SCHEDULED: RequiredParams<'0'>
	/**
	 * {​n​u​m​D​o​n​e​}​ ​o​f​ ​{​n​u​m​T​o​t​a​l​}​ ​c​a​r​d​s​ ​d​o​n​e
	 * @param {unknown} numDone
	 * @param {unknown} numTotal
	 */
	OF_NUM_CARDS_DONE: RequiredParams<'numDone' | 'numTotal'>
	/**
	 * L​a​n​g​u​a​g​e
	 */
	LANGUAGE: string
	/**
	 * L​a​n​g​u​a​g​e​ ​S​e​l​e​c​t​o​r
	 */
	LANGUAGE_SELECTOR: string
	/**
	 * E​x​p​o​r​t​ ​D​a​t​a
	 */
	EXPORT_DATA: string
	STUDY: {
		/**
		 * S​h​o​w​ ​A​n​s​w​e​r
		 */
		SHOW_ANSWER: string
		/**
		 * Q​u​e​s​t​i​o​n
		 */
		QUESTION: string
		/**
		 * A​n​s​w​e​r
		 */
		ANSWER: string
		/**
		 * N​o​ ​c​a​r​d​s​ ​d​u​e
		 */
		NO_CARDS: string
		ANSWER_OPTIONS: {
			/**
			 * A​g​a​i​n
			 */
			AGAIN: string
			/**
			 * H​a​r​d
			 */
			HARD: string
			/**
			 * G​o​o​d
			 */
			GOOD: string
			/**
			 * E​a​s​y
			 */
			EASY: string
		}
	}
	ERROR_PAGE: {
		/**
		 * U​n​e​x​p​e​c​t​e​d​ ​E​r​r​o​r
		 */
		ERROR: string
		/**
		 * R​e​s​e​t
		 */
		RESET: string
		/**
		 * N​o​t​ ​F​o​u​n​d
		 */
		NOT_FOUND: string
	}
	COMPONENTS: {
		FILE_DROP_ZONE: {
			/**
			 * C​l​i​c​k​ ​t​o​ ​s​e​l​e​c​t​ ​a​ ​f​i​l​e
			 */
			CLICK_TO_SELECT: string
			/**
			 * o​r​ ​d​r​a​g​ ​a​n​d​ ​d​r​o​p
			 */
			OR_DROP: string
		}
	}
	CARD_EDITOR: {
		/**
		 * F​r​o​n​t
		 */
		FRONT: string
		/**
		 * B​a​c​k
		 */
		BACK: string
		/**
		 * E​d​i​t​i​n​g​ ​c​a​r​d
		 */
		IS_EDITING: string
		/**
		 * C​a​n​c​e​l
		 */
		CANCEL_EDITING: string
		/**
		 * S​a​v​e
		 */
		SAVE: string
	}
	/**
	 * C​o​l​l​e​c​t​i​o​n
	 */
	COLLECTION: string
	COLLECTIONS: {
		/**
		 * A​r​e​ ​y​o​u​ ​s​u​r​e​?​ ​T​h​i​s​ ​w​i​l​l​ ​d​e​l​e​t​e​ ​a​l​l​ ​d​o​c​u​m​e​n​t​s​ ​a​n​d​ ​c​a​r​d​s​ ​i​n​ ​t​h​i​s​ ​c​o​l​l​e​c​t​i​o​n​.
		 */
		DELETE_COLLECTION_WARNING: string
	}
	DOCUMENTS: {
		/**
		 * A​r​e​ ​y​o​u​ ​s​u​r​e​?​ ​T​h​i​s​ ​w​i​l​l​ ​a​l​s​o​ ​d​e​l​e​t​e​ ​a​l​l​ ​c​a​r​d​s​ ​i​n​ ​t​h​i​s​ ​d​o​c​u​m​e​n​t​.
		 */
		DELETE_DOCUMENTS_WARNING: string
	}
}

export type TranslationFunctions = {
	ROUTES: {
		/**
		 * Home
		 */
		HOME: () => LocalizedString
		/**
		 * Documents
		 */
		DOCUMENTS: () => LocalizedString
		/**
		 * Collections
		 */
		COLLECTIONS: () => LocalizedString
		/**
		 * Study
		 */
		STUDY: () => LocalizedString
		/**
		 * Settings
		 */
		SETTINGS: () => LocalizedString
	}
	/**
	 * Document
	 */
	DOCUMENT: () => LocalizedString
	/**
	 * Combined
	 */
	COMBINED: () => LocalizedString
	SAMPLE_CARDS: {
		CARD1: {
			/**
			 * <h2>How can I get started and create new flashcards?</h2>
			 */
			front: () => LocalizedString
			/**
			 * <p>To create your first flashcards, follow these steps:
		      <ul>
		        <li>First, add a <b>new collection</b> <a href="/collections">here</a></li>
		        <li>Select the newly created collection and <b>add a PDF document</b> to the collection.</li>
		        <li>Click on the added document. You're now in the <b>editor</b> and can <b>design flashcards</b> manually or with image snippets from the PDF.</li>
		      </ul>
		    </p>
		    
			 */
			back: () => LocalizedString
		}
		CARD2: {
			/**
			 * <h2>Why do I need to select a PDF to create flashcards?</h2>
			 */
			front: () => LocalizedString
			/**
			 * <p>In cardflash, <b>flashcards are always directly linked to the source</b> of the information.
		      <br/>
		      This way, when studying, you can easily read more information or clarify any uncertainties.
		      <br/>
		      <br/>
		      Currently, only PDF files are supported as source material. However, you can also export websites or other sources as PDFs and use them in cardflash this way.</p>
	
			 */
			back: () => LocalizedString
		}
		CARD3: {
			/**
			 * <h2>Can I change the interface language?</h2>
			 */
			front: () => LocalizedString
			/**
			 * <p>Sure thing! Head over to the <a href="/settings">settings</a> to change the language.
		      <br/>
		      Currently, English and German are available.</p>
			 */
			back: () => LocalizedString
		}
	}
	HOME: {
		/**
		 * Welcome to
		 */
		WELCOME: () => LocalizedString
		/**
		 * Right now, you do not have any collections, documents or flashcards stored.
		 */
		NO_CARDS_STORED: () => LocalizedString
		/**
		 * To start creating flashcards, add your first collection
		 */
		ADD_FIRST_COLLECTION: () => LocalizedString
		/**
		 * To study all your created flashcards, click
		 */
		STUDY_FLASHCARDS: () => LocalizedString
		/**
		 * here
		 */
		HERE: () => LocalizedString
		/**
		 * Example flashcards
		 */
		EXAMPLE_FLASHCARDS: () => LocalizedString
		/**
		 * Below, we present a few sample flashcards showcasing the study interface and providing additional information about cardflash.
		 */
		EXAMPLE_FLASHCARDS_DESC: () => LocalizedString
	}
	/**
	 * Back
	 */
	GO_BACK: () => LocalizedString
	/**
	 * Back to collection
	 */
	GO_BACK_TO_COLLECTION: () => LocalizedString
	/**
	 * Welcome!
	 */
	WELCOME: () => LocalizedString
	/**
	 * Add
	 */
	ADD: () => LocalizedString
	/**
	 * Edit
	 */
	EDIT: () => LocalizedString
	/**
	 * Delete
	 */
	DELETE: () => LocalizedString
	/**
	 * Save
	 */
	SAVE: () => LocalizedString
	/**
	 * Cancel
	 */
	CANCEL: () => LocalizedString
	/**
	 * Name
	 */
	NAME: () => LocalizedString
	/**
	 * Shuffle
	 */
	SHUFFLE: () => LocalizedString
	/**
	 * View PDF
	 */
	VIEW_PDF: () => LocalizedString
	/**
	 * Cards
	 */
	CARDS: () => LocalizedString
	/**
	 * Flashcards for
	 */
	CARDS_FOR: () => LocalizedString
	/**
	 * Study all
	 */
	STUDY_ALL: () => LocalizedString
	/**
	 * View all
	 */
	VIEW_ALL: () => LocalizedString
	/**
	 * {0} cards scheduled
	 */
	NUM_CARDS_SCHEDULED: (arg0: unknown) => LocalizedString
	/**
	 * {numDone} of {numTotal} cards done
	 */
	OF_NUM_CARDS_DONE: (arg: { numDone: unknown, numTotal: unknown }) => LocalizedString
	/**
	 * Language
	 */
	LANGUAGE: () => LocalizedString
	/**
	 * Language Selector
	 */
	LANGUAGE_SELECTOR: () => LocalizedString
	/**
	 * Export Data
	 */
	EXPORT_DATA: () => LocalizedString
	STUDY: {
		/**
		 * Show Answer
		 */
		SHOW_ANSWER: () => LocalizedString
		/**
		 * Question
		 */
		QUESTION: () => LocalizedString
		/**
		 * Answer
		 */
		ANSWER: () => LocalizedString
		/**
		 * No cards due
		 */
		NO_CARDS: () => LocalizedString
		ANSWER_OPTIONS: {
			/**
			 * Again
			 */
			AGAIN: () => LocalizedString
			/**
			 * Hard
			 */
			HARD: () => LocalizedString
			/**
			 * Good
			 */
			GOOD: () => LocalizedString
			/**
			 * Easy
			 */
			EASY: () => LocalizedString
		}
	}
	ERROR_PAGE: {
		/**
		 * Unexpected Error
		 */
		ERROR: () => LocalizedString
		/**
		 * Reset
		 */
		RESET: () => LocalizedString
		/**
		 * Not Found
		 */
		NOT_FOUND: () => LocalizedString
	}
	COMPONENTS: {
		FILE_DROP_ZONE: {
			/**
			 * Click to select a file
			 */
			CLICK_TO_SELECT: () => LocalizedString
			/**
			 * or drag and drop
			 */
			OR_DROP: () => LocalizedString
		}
	}
	CARD_EDITOR: {
		/**
		 * Front
		 */
		FRONT: () => LocalizedString
		/**
		 * Back
		 */
		BACK: () => LocalizedString
		/**
		 * Editing card
		 */
		IS_EDITING: () => LocalizedString
		/**
		 * Cancel
		 */
		CANCEL_EDITING: () => LocalizedString
		/**
		 * Save
		 */
		SAVE: () => LocalizedString
	}
	/**
	 * Collection
	 */
	COLLECTION: () => LocalizedString
	COLLECTIONS: {
		/**
		 * Are you sure? This will delete all documents and cards in this collection.
		 */
		DELETE_COLLECTION_WARNING: () => LocalizedString
	}
	DOCUMENTS: {
		/**
		 * Are you sure? This will also delete all cards in this document.
		 */
		DELETE_DOCUMENTS_WARNING: () => LocalizedString
	}
}

export type Formatters = {}
